### ISSUE TITLE
out of memory in the stage of training

### ISSUE THREAD

**Issue by ouyangpingbu** [huanghoujing/AlignedReID-Re-Production-Pytorch#1]
hi, I always get this error “RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1503961620703/work/torch/lib/THC/generic/THCStorage.cu:66” . is the batchsize too big? How can I change it?

**Comment by huanghoujing** [comment]
The default setting in `script/tri_loss/train_cfg.py` requires over 9000MB:
- im_h x im_w = 256 x 128
- batch size = 128 images (32 id x 4 images/id)

You can decrease the number of ids in `script/tri_loss/train_cfg.py` to 16:
```python
self.ids_per_batch = 16
```

However, I find larger batch size tends to have better performance. Thus, if you use GPU with capacity of 6GB, you can leave the batch size unchanged but use two GPUs by setting the `sys_device_ids` accordingly. E.g. use the first two GPUs to train with Triplet Global Loss:

```bash
python script/tri_loss/train.py \
-d '(0, 1,)' \
-r 1 \
--dataset market1501 \
-glw 1.0 \
-llw 0 \
--log_to_file
```
