### ISSUE TITLE
这个错误是什么意思？

### ISSUE THREAD

**Issue by Tz-MacWang** [huanghoujing/AlignedReID-Re-Production-Pytorch#10]
root@omnisky:/raid/wtz/AlignedReID-Re-Production-Pytorch# python script/dataset/transform_cuhk03.py \
> --zip_file ~/Dataset/cuhk03/cuhk03_release.zip \
> --train_test_partition_file ~/Dataset/cuhk03/re_ranking_train_test_split.pkl \
> --save_dir ~/Dataset/cuhk03
Extracting zip file
Saving images 1400/1467
Traceback (most recent call last):
  File "script/dataset/transform_cuhk03.py", line 152, in <module>
    transform(zip_file, train_test_partition_file, save_dir)
  File "script/dataset/transform_cuhk03.py", line 84, in transform
    raise RuntimeError('Train/test partition file should be provided.')
RuntimeError: Train/test partition file should be provided.

**Comment by huanghoujing** [comment]
有一个文件指定了哪些图片是训练集，哪些是测试集，这个是由new train/test protocol的划分决定的。运行脚本时，这个文件由参数`--train_test_partition_file`设定。在你上面的错误中，指定到了`~/Dataset/cuhk03/re_ranking_train_test_split.pkl`，你必须把这个文件（可以从[这里](https://pan.baidu.com/s/1miuxl3q)下载）放到这个位置才行。

**Comment by Tz-MacWang** [comment]
谢谢，已解决，还有一个问题出现了
当我运行
python script/tri_loss/train.py -d '(0,)' --dataset market1501 --normalize_feature false -glw 1 -llw 0 -idlw 0 --only_test true --exp_dir SPECIFY_AN_EXPERIMENT_DIRECTORY_HERE --model_weight_file THE_DOWNLOADED_MODEL_WEIGHT_FILE
之后，报了这个错误，请问我需要改动哪个地方？
Traceback (most recent call last):
  File "script/tri_loss/train.py", line 404, in <module>
    main()
  File "script/tri_loss/train.py", line 134, in main
    TMO(modules_optims)
  File "build/bdist.linux-x86_64/egg/aligned_reid/utils/utils.py", line 154, in __call__
  File "build/bdist.linux-x86_64/egg/aligned_reid/utils/utils.py", line 131, in may_transfer_modules_optims
TypeError: cuda() got an unexpected keyword argument 'device_id'

**Comment by fighting-liu** [comment]
看看pytorch 版本是不是和要求的一样，不同pytorch版本可能参数名不一样

**Comment by huanghoujing** [comment]
是的，这是pytorch版本的问题，这个工程用的是pytorch 0.1.12。

**Comment by Tz-MacWang** [comment]
已解决，谢谢

**Comment by Tz-MacWang** [comment]
又恬不知耻地来问问题了
Traceback (most recent call last):
  File "script/tri_loss/train.py", line 404, in <module>
    main()
  File "script/tri_loss/train.py", line 108, in main
    model_w = DataParallel(model)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 48, in __init__
    output_device = device_ids[0]
IndexError: list index out of range

**Comment by huanghoujing** [comment]
你是不是没有用显卡，那得把`train.py`第108行`model_w = DataParallel(model)`改为`model_w = model`。因为`DataParallel`只能在有显卡的情况下才能调用。这里是我考虑不周的一个地方。

**Comment by Tz-MacWang** [comment]
在docker中运行，不知有没有其他的解决办法

**Comment by huanghoujing** [comment]
首先检查一下你这个环境可不可以调用CUDA，试一下这个例子
```python
import torch

x = torch.ones(3, 4).cuda()
print(x)
```

**Comment by Tz-MacWang** [comment]
不行，在docker里无法调用CUDA

**Comment by huanghoujing** [comment]
这样，那得先调通这一步。docker我没用过，不了解。。。

**Comment by Tz-MacWang** [comment]
再次感谢您对我的帮助，我在实体机上已能正常运行，十分感谢

**Comment by huanghoujing** [comment]
不客气 : )

**Comment by ChunfeiMa** [comment]
@Tz-MacWang 
how could you solve the problem of "TypeError: cuda() got an unexpected keyword argument 'device_id'"?

**Comment by huanghoujing** [comment]
@ChunfeiMa After upgrading to pytorch 0.3 or higher, this problem would be solved.
