### ISSUE TITLE
Hope this code can be compatible with pytorch 0.2 or 0.3

### ISSUE THREAD

**Issue by YihangLou** [huanghoujing/AlignedReID-Re-Production-Pytorch#11]
Dear Author:
         This code is written elegantly. If it could be compatible with pytorch 0.2 or 0.3, it would be better.

**Comment by huanghoujing** [comment]
Thank you for attention! I am going to upgrade it to pytorch 0.3 recently.

**Comment by TaihuLight** [comment]
I suggest that the code use PIL(Pillow) instead of matplotlib, because matplotlib can be offline installed successfully  on server,  but PIL(Pillow)  is necessary for Pytorch.

**Comment by huanghoujing** [comment]
Yes, PIL is a good idea. Thanks,

**Comment by huanghoujing** [comment]
The project is already upgraded to Pytorch v0.3. It's not backward compatible with v0.1.
