### ISSUE TITLE
可有提供测试代码？

### ISSUE THREAD

**Issue by Tz-MacWang** [huanghoujing/AlignedReID-Re-Production-Pytorch#12]
请问，我如何可以进行测试，直观地查看我的网络训练情况？

**Comment by huanghoujing** [comment]
`train.py`在训练结束的时候会对测试集进行测试的。你也可以每隔几个epoch测试一次。

**Comment by Tz-MacWang** [comment]
我的意思是比较直观的，比如我扔一张图片进去，它能返回找到的类似图片的名字或者直接显示图片

**Comment by huanghoujing** [comment]
这个实现起来很简单的，我后续加上，你也可以先实现。

就是给一个图像`x`，用训好的网络提取它的特征`f(x)`，然后对`gallery`集的每一张图像`y_i`也提取特征`f(y_i)`，计算`f(x)`和每一个`f(y_i)`的欧氏距离，对距离从小到大排序就可以得到一个排序列表，然后把这些图像显示出来就好了。

**Comment by Tz-MacWang** [comment]
谢谢

**Comment by huanghoujing** [comment]
@Tz-MacWang，我提供了[测试的demo](https://github.com/huanghoujing/person-reid-triplet-loss-baseline#visualize-ranking-list)，可以显示排序列表，直观看出行人检索的效果。

**Comment by Tz-MacWang** [comment]
谢谢
