### ISSUE TITLE
可否告知两个单词的翻译？

### ISSUE THREAD

**Issue by Tz-MacWang** [huanghoujing/AlignedReID-Re-Production-Pytorch#13]
在您的代码中找到两个单词，怎么翻译都感觉不符您意：
query
gallery
query-gallery
query-query
gallery-gallery
可否告知在您的代码里，这两个单词所代表的含义？
感激不尽！

**Comment by huanghoujing** [comment]
单词的意思：`query`是`查询`，`gallery`是`画廊`。在`ReID`（re-identification）的测试过程中，给定一张图像`x`，要从一堆图像`T`中找出跟`x`相同ID（identity，身份）的图像来。这里`x`就是`query`，也有写作`probe`的；这里的一堆图像`T`就是`gallery`集。这些词汇应该是来自于图像检索领域。

**Comment by Tz-MacWang** [comment]
谢谢
