### ISSUE TITLE
Image Pre-processing

### ISSUE THREAD

**Issue by Phoebe-star** [huanghoujing/AlignedReID-Re-Production-Pytorch#21]
how do you set the dataset size?
you directly resize to 224x224? I find the ratio is  strange and the image is strange

do crop the image then  resize to 224x224?I find do it ,it will happen the head and feet of person disappear.

how do you   do data extend?

**Comment by huanghoujing** [comment]
The processing steps I used:
- resizing to `w x h = 128 x 256`
- subtracting image mean
- dividing by image std
- horizontally flipping with probability 0.5

No cropping is used. Though the code provides the option to use cropping, I found it did not benefit performance in my experiments.

**Comment by Phoebe-star** [comment]
do you have use resnet or googlenet or VGG .... with tensorflow  and  it is trainable  for  imagenet

**Comment by huanghoujing** [comment]
I only use ResNet-50 here. I once tried Inception-V3 for identification loss and it's worse than ResNet-50.

**Comment by Phoebe-star** [comment]
I find use the  trainable resnet 50  ,if I set the batch size 128 , it express 128x3 images, because triplet.
the network will out of memory.

**Comment by huanghoujing** [comment]
128 triplets are formed **among** this batch of 128 images, so only 128 images are needed and the memory is enough.
