### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by weilanShi** [huanghoujing/AlignedReID-Re-Production-Pytorch#24]
When I run the program, there is a mistake ；ModuleNotFoundError: No module named 'aligned_reid'，What is the reason for it ？ I've just been in contact with Python and hope that the question can be answered,thank you

**Comment by huanghoujing** [comment]
Thanks for your attention!

After cloning the repository by `git clone https://github.com/huanghoujing/AlignedReID-Re-Production-Pytorch.git`, you have to enter the project directory by `cd AlignedReID-Re-Production-Pytorch` before running python scripts.

Did you follow these steps?
