### ISSUE TITLE
image input size problem

### ISSUE THREAD

**Issue by chegnyanjun** [huanghoujing/AlignedReID-Re-Production-Pytorch#26]
我有点不是很理解，为什么您的代码实现的时候，图像的输入是256x128的尺寸呀，原论文不是224x224吗；顺便问一下改成你这样的是有什么优点吗，以及图像的不同尺寸对最终效果有影响吗。希望您能帮我解惑，谢谢啦！

**Comment by huanghoujing** [comment]
你好，多谢关注！
之前有论文做的ReID多分类模型，说过128x256比224x224效果更好，所以我就用了128x256. 我觉得AlignedReID应该适用于不同的baseline，不至于改变图像的尺寸会有那么大的影响，所以就没对比两种尺寸的区别。我这只是猜测，改一改图像尺寸真的就有很大影响也说不准。你如果感兴趣可以试一下224x224的图像。

**Comment by chegnyanjun** [comment]
好的，谢谢啦，非常感谢您的回答！
