### ISSUE TITLE
运用tensorboard得出的网址无效？

### ISSUE THREAD

**Issue by liuxiaohua123** [huanghoujing/AlignedReID-Re-Production-Pytorch#32]
-  您好，按照你所写的，我们得出logs文件之后，运用tensorboard得出的网址是https://9408:6006，请问是因为这个网址是错误的打不开还是怎么回事呢？

**Comment by huanghoujing** [comment]
您好，默认的端口是6006，在浏览器访问server-ip:6006即可，这里server-ip是存log的电脑的ip。比如ip是168.11.22.33，那就在浏览器访问168.11.22.33:6006即可。但是必须浏览器所在的电脑能够访问到这个ip。

**Comment by liuxiaohua123** [comment]
谢谢了。已成功解决了。
