### ISSUE TITLE
The generalization ability of the model

### ISSUE THREAD

**Issue by lonelylingoes** [huanghoujing/AlignedReID-Re-Production-Pytorch#33]
Have you ever tried that trainning on one dataset, and test on another dataset?
The result I tried is abjective.

**Comment by huanghoujing** [comment]
Yes, the cross dataset testing result is unreasonably bad. [An old issue](https://github.com/huanghoujing/AlignedReID-Re-Production-Pytorch/issues/14) in the repository talked about this, though it is in Chinese.
