### ISSUE TITLE
训练集id数和ids_per_batch的问题

### ISSUE THREAD

**Issue by ShiinaMitsuki** [huanghoujing/AlignedReID-Re-Production-Pytorch#37]
发现一个训练数据集id数量和训练时ids_per_batch的设定的问题：
`train_set_ids % ids_per_batch = 1的时候会导致整个epoch最后一个batch只有一个id，此时triloss时会没有负样本，故而会报错`

**Comment by huanghoujing** [comment]
您好，多谢反馈！我把`train_final_batch`改成了`False`，可以解决这个问题。
