### ISSUE TITLE
Performance dropped with model trained on the combined dataset (market1501+duke+cuhk03)?

### ISSUE THREAD

**Issue by zeyu-liu** [huanghoujing/AlignedReID-Re-Production-Pytorch#38]
Thanks for the reproduction code!

I trained a model with triploss (use train.py), combined train data (market1501, duke and cuhk03), and the other parameters kept same as the settings to train only on market1501. I found that both the mAP and rank1 are ~1% less than the result of trained only on market1501. Should I tune the parameters MORE CAREFULLY to get a better performance?

btw, I have reproduced the result only trained on market1501. (got 87.14% rank-1 and 71.36% mAP w/o R.R.)

Thank you!

**Comment by huanghoujing** [comment]
Thanks for your interest! I have similar result as yours when training on the combined dataset. After training on the combined dataset, you may try to finetune the model on each dataset separately (I didn't try this yet).

**Comment by zeyu-liu** [comment]
OK, I see😀. Thanks for the reply.
