### ISSUE TITLE
can't find "create_dataset" this file

### ISSUE THREAD

**Issue by hsqaihkl** [huanghoujing/AlignedReID-Re-Production-Pytorch#39]
@huanghoujing hi, I run the train.py but in the 19 lines :“from aligned_reid.dataset import create_dataset”，but i can't find this file in "dataset" .

**Comment by huanghoujing** [comment]
Thank you for your attention! This `create_dataset` is defined in file [`aligned_reid/dataset/__init__.py`](https://github.com/huanghoujing/AlignedReID-Re-Production-Pytorch/blob/fbce739e4663ae0ab83004ced48245ff61d5ac74/aligned_reid/dataset/__init__.py#L12).

**Comment by hsqaihkl** [comment]
Ok ，I find it ！
Hi，houjing，I have run it in my project to test it Whether it in real time ，but  I test it and print time ，it create the feate use time 804ms.
my system :1050ti,7700HK,win10 ,cuda9.0 ，cudnn7.1，python3.6, torch0.4
is that my computer too low？

**Comment by hsqaihkl** [comment]
@huanghoujing 
Ok ，I have foud it ！
Hi，houjing，I have run it in my project to test it Whether it in a real time ，but I test it and print time ，it use more time in creating the feate, use time 804ms.
my system :1050ti,7700HK,win10 ,cuda9.0 ，cudnn7.1，python3.6, torch0.4
is that my computer too low？

**Comment by hsqaihkl** [comment]
this is the creat feat code:

ims_var = Variable(transer_var_tensor(torch.from_numpy(images), self.device_id).float(), volatile=True)
feats,_ = self.model(ims_var)[:2]
feats = feats.data.cpu().numpy()


could you help me to improve it？

**Comment by huanghoujing** [comment]
Your code looks alright. Maybe the speed is determined by the machine.

**Comment by hsqaihkl** [comment]
Ok Thks!
