### ISSUE TITLE
What is the difference between this project and person-reid-triplet-loss-baseline?

### ISSUE THREAD

**Issue by cesarandreslopez** [huanghoujing/AlignedReID-Re-Production-Pytorch#45]
@huanghoujing you seem to be actively maintaining both projects and both work very well. I'm wondering what are the main differences between both projects?

**Comment by huanghoujing** [comment]
Hi, thanks for your attention. 
- Repository `AlignedReID-Re-Production-Pytorch` is mainly for exploring the algorithms used in paper AlignedReID, including shortest distance and mutual learning. So it contains some customized code that is only necessary when using AlignedReID.  
- Repository `person-reid-triplet-loss-baseline` is a **clean** version of training triplet loss, which is straightforward to read.
- The triplet loss baselines in two repositories are the same, except that `person-reid-triplet-loss-baseline` also tries a trick (i.e. larger resolution in the last conv layer of resnet-50) and achieves good results. So if someone is looking for a strong triplet loss baseline, I think `person-reid-triplet-loss-baseline` is a good one.

**Comment by cesarandreslopez** [comment]
Excellent! Thank you!
