### ISSUE TITLE
Assertion Error: During testing with Pre-trained model

### ISSUE THREAD

**Issue by kai-kaushik** [huanghoujing/AlignedReID-Re-Production-Pytorch#52]
`
Traceback (most recent call last):

  File "script/experiment/train.py", line 632, in <module>
    main()

  File "script/experiment/train.py", line 316, in main
    train_set = create_dataset(**cfg.train_set_kwargs)

  File "./aligned_reid/dataset/__init__.py", line 54, in create_dataset
    partitions = load_pickle(partition_file)

  File "./aligned_reid/utils/utils.py", line 24, in load_pickle
    assert osp.exists(path)

AssertionError
`
Hi, I am getting this error when Im trying to run the code to test on the market-1501 dataset. Im new to Pytorch, so please help. Im using PyTorch 3 and python 2.7 as directed in the code. Thanks

**Comment by Malathi15** [comment]
@Kumara-Kaushik Have you solved this issue?
I got the same error when i tried to run the code. What should i do to overcome this issue..

Thanks in advance

**Comment by kumar15011995** [comment]
@Malathi15 , sorry but i ran this code a while back, not sure what exactly i did. So i wont be able to help you out for now. Hope you find a solution, if you do, maybe post the answer here so others wont face the same issue. Sorry about that!
