### ISSUE TITLE
CUHK03和DUKE上的识别率

### ISSUE THREAD

**Issue by PayneYong** [huanghoujing/AlignedReID-Re-Production-Pytorch#64]
大家有在cuhk03和duke上训练并测试吗？在其他地方看到的复现代码https://github.com/michuanhaohao/AlignedReID，在market1501上的性能还能说的过去，但是到了其他两个数据集上好像比market1501和论文中公布的cuhk03的性能差了很多，是不是论文所述的方法只是market1501表现的好些，在其他数据集上就效果就没那么好？

**Comment by jszgz** [comment]
我用黄老师默认的参数跑出来cmc1只有六十多
